spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/wallet
        username: postgresql
        password: postgresql
    kafka:
        bootstrap-servers: localhost:9092
    flyway:
        url: jdbc:postgresql://localhost:5432/wallet
        locations: classpath:db/migration
        main:
            allow-bean-definition-overriding: true

logging:
    level:
        org.springframework: INFO
        org.springframework.kafka: DEBUG
